"""Add original_filename column

Revision ID: cf4e740bd986
Revises: 4a339021f2c4
Create Date: 2026-05-18 01:02:02.764632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4e740bd986'
down_revision: Union[str, Sequence[str], None] = '4a339021f2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('original_filename', sa.String(length=255), nullable=True, comment='Event snapshot/image name'))
    op.drop_column('events', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Path to the saved event snapshot/image'))
    op.drop_column('events', 'original_filename')
    # ### end Alembic commands ###
