"""Rename original_filename column to storage_filename

Revision ID: d08a136a15df
Revises: cf4e740bd986
Create Date: 2026-05-18 01:29:02.456363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08a136a15df'
down_revision: Union[str, Sequence[str], None] = 'cf4e740bd986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('storage_filename', sa.String(length=255), nullable=True, comment='Event snapshot/image name'))
    op.drop_column('events', 'original_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Event snapshot/image name'))
    op.drop_column('events', 'storage_filename')
    # ### end Alembic commands ###
